const callbacks = {
    CHECK_SEARCHES: 'getSearches',
    CHANGE_LANG: 'changeLang',
    CONTINUE: 'continue',
    SET_SEARCH_FLAG_TRUE: 'setSearchesFlagTrue',
    SET_SEARCH_FLAG_FALSE: 'setSearchesFlagFalse',
    property_type: {
        FLAT: `property_type:Flat`,
        ROOM: `property_type:Room`,
        HOUSE: `property_type:House`,
    },
    number_of_rooms: {
        ONE: 'number_of_rooms:1',
        TWO: 'number_of_rooms:2',
        THREE: 'number_of_rooms:3',
        FOUR_PLUS: 'number_of_rooms:4+',
    },
    ad_type: {
        OWNER: 'ad_type:Owner',
        AGENCY: 'ad_type:Agency',
        ANY: 'ad_type:Any',
    },
    SET_FILTERS: 'setFilters',
    SET_NO_FILTERS: 'setNoFilters',
    cities: {
        WARSHAVA: 'Warszawa',
        KRAKOW: 'Kraków',
        POZNAN: 'Poznań',
        LODZ: 'Lódz',
        KATOWICE: 'Katowice',
        SZCZECIN: 'Szczecin',
        BYDGOSZCZ: 'Bydgoszcz',
        RZESZOW: 'Rzeszów',
        GDYNIA: 'Gdynia',
        TORUN: 'Toruń',
        KIELCE: 'Kielce',
        GLIWICE: 'Gliwice',
        RADOM: 'Radom',
        BIELSKOBIALA: 'Bielsko-Biała',
        WROCLAW: 'Wrocław',
        GDANSK: 'Gdańsk',
        LUBLIN: 'Lublin',
        BIALYSTOK: 'Białystok',
        OLSZTYN: 'Olsztyn',
        CZESTOCHOWA: 'Częstochowa',
        ZIELONAGORA: 'Zielona Góra',
    },
    NO_CITY: 'no_city',
    districts: {
        WARSHAVA: {
            BEMOWO: 'Bemowo',
            BIALOLEKA: 'Białołęka',
            BIELANY: 'Bielany',
            MOKOTOW: 'Mokotów',
            OCHOTA: 'Ochota',
            PRAGA_POLUDNIE: 'Praga-Południe',
            PRAGA_POLNOC: 'Praga-Północ',
            REMBERTOW: 'Rembertów',
            SRODMIESCIE: 'Śródmieście',
            TARGOWEK: 'Targówek',
            URSUS: 'Ursus',
            URSYNOW: 'Ursynów',
            WAWER: 'Wawer',
            WESOLA: 'Wesoła',
            WILANOW: 'Wilanów',
            WLOCHY: 'Włochy',
            WOLA: 'Wola',
            ZOLIBORZ: 'Żoliborz',
        },
        KRAKOW: {
            BIENCZYCE: 'Bieńczyce',
            BIEZANOW_PROKOCIM: 'Bieżanów-Prokocim',
            BRONOWICE: 'Bronowice',
            CZYZYNY: 'Czyżyny',
            DEBNIKI: 'Dębniki',
            GRZEGORZKI: 'Grzegórzki',
            KROWODRZA: 'Krowodrza',
            LAGIEWNIKI_BOREK_FALECKI: 'Łagiewniki-Borek Fałęcki',
            MISTRZEJOWICE: 'Mistrzejowice',
            NOWA_HUTA: 'Nowa Huta',
            PODGORZE: 'Podgórze',
            PODGORZE_DUCHACKIE: 'Podgórze Duchackie',
            PRADNIK_BIALY: 'Prądnik Biały',
            PRADNIK_CZERWONY: 'Prądnik Czerwony',
            STARE_MIASTO: 'Stare Miasto',
            SWOSZOWICE: 'Swoszowice',
            WZGORZA_KRZESLAWE: 'Wzgórza Krzesławickie',
            ZWIERZYNIEC: 'Zwierzyniec',
        },
        WROCLAW: {
            BROCHOW: 'Brochów',
            BISKUPIN_SADOWSKIEGO: 'Biskupin-Sienkiewicza-Sądowskiego',
            FABRYCZNA: 'Fabryczna',
            GRABISZYN_PARTYNICE: 'Grabiszyn-Partynice',
            KLECINA: 'Klecina',
            KORZENNA: 'Korzeńsko',
            KRZYKI_PARTYNICE: 'Krzyki-Partynice',
            LESNICA: 'Leśnica',
            MARINO: 'Marino',
            MUCHOLOWICE: 'Muchobór Wielki-Muchobór Mały',
            NOWY_DWOR: 'Nowy Dwór',
            OLTASZYN: 'Ołtaszyn',
            OSOBOWICE_RACONTERIA: 'Osobowice-Rędzin',
            OPOLE: 'Opole',
            POLANIEC: 'Polan',
            PRACZE_ODRZANSKIE: 'Pracze Odrzańskie',
            SOBOCE: 'Sobótka',
            SZCZEPIN: 'Szczepin',
            STARE_MIASTO: 'Stare Miasto',
            STRACHOWICE: 'Strachowice',
            SRODMIESCIE: 'Śródmieście',
            SWIEBODZICE: 'Świebodzice',
            SZCZODRE: 'Szczodre',
            TARNOWSKIE_GORY: 'Tarnogaj',
            WROCLAW_POLESIE: 'Wrocław Polesie',
            ZERNIKI: 'Żerniki',
            ZLOTNO: 'Złotniki',
        },
        POZNAN: {
            CHARTOWO: 'Chartowo',
            DEBIEC: 'Dębiec',
            GORCZYN: 'Górczyn',
            GRUNWALD: 'Grunwald',
            JEZYCE: 'Jeżyce',
            JUNIKOWO: 'Junikowo',
            KOMANDORIA: 'Komandoria',
            LACINA: 'Łacina',
            LAWICA: 'Ławica',
            LAZARZ: 'Łazarz',
            NARAMOWICE: 'Naramowice',
            OGRODY: 'Ogrody',
            PIATKOWO: 'Piątkowo',
            PODOLANY: 'Podolany',
            RATAJE: 'Rataje',
            SMOCHOWICE: 'Smochowice',
            SOLACZ: 'Sołacz',
            STARE_MIASTO: 'Stare Miasto',
            STAROLEKA: 'Starołęka',
            STRZESZYN: 'Strzeszyn',
            SZCZEPANKOWO: 'Szczepankowo',
            SRODKA: 'Śródka',
            WARSZAWSKIE: 'Warszawskie',
            WILDA: 'Wilda',
            WINIARY: 'Winiary',
            WINOGRADY: 'Winogrady',
        },
        GDANSK: {
            ANIOLKI: 'Aniołki',
            BRETOWO: 'Brętowo',
            BRZEZNO: 'Brzeźno',
            CHELM_GDANSK_POLUDNIE: 'Chełm z dzielnicą Gdańsk Południe',
            JASIEN: 'Jasień',
            KOKOSZKI: 'Kokoszki',
            KRAKOWIEC_GORKI_ZACHODNIE: 'Krakowiec - Górki Zachodnie',
            LETNICA: 'Letnica',
            MATARNIA: 'Matarnia',
            MLYNISKA: 'Młyniska',
            NOWY_PORT: 'Nowy Port',
            OLIWA: 'Oliwa',
            OLSZYNKA: 'Olszynka',
            ORUNIA_SW_WOJCIECH_LIPCE: 'Orunia - Św. Wojciech - Lipce',
            OSOWA: 'Osowa',
            PIECKI_MIGOWO: 'Piecki-Migowo',
            PRZYMORZE_MALE: 'Przymorze Małe',
            PRZYMORZE_WIELKIE: 'Przymorze Wielkie',
            RUDNIKI: 'Rudniki',
            SIEDLCE: 'Siedlce',
            STOGI_Z_PRZEROBKA: 'Stogi z Przeróbką',
            STRZYZA: 'Strzyża',
            SUCHANINO: 'Suchanino',
            SRODMIESCIE: 'Śródmieście',
            UJESCISKO_LOSTOWICE: 'Ujeścisko - Łostowice',
            VII_DWOR: 'VII Dwór',
            WRZESZCZ: 'Wrzeszcz',
            WYSPA_SOBIESZEWSKA: 'Wyspa Sobieszewska',
            WZGORZE_MICKIEWICZA: 'Wzgórze Mickiewicza',
            ZASPA_MLYNIEC: 'Zaspa Młyniec',
            ZASPA_ROZSTAJE: 'Zaspa Rozstaje',
            ZABIANKA_WEJHERA_JELITKOWO_TYSIACLECIA: 'Żabianka - Wejhera - Jelitkowo - Tysiąclecia',
        },
        GDYNIA: {
            BABIE_DOLY: 'Babie Doły',
            CHWARZNO_WICZLINO: 'Chwarzno-Wiczlino',
            CHYLONIA: 'Chylonia',
            CISOWA: 'Cisowa',
            DABROWA: 'Dąbrowa',
            DZIALKI_LESNE: 'Działki Leśne',
            GRABOWEK: 'Grabówek',
            KAMIENNA_GORA: 'Kamienna Góra',
            KARWINY: 'Karwiny',
            LESZCZYNKI: 'Leszczynki',
            MALY_KACK: 'Mały Kack',
            OBLUZE: 'Obłuże',
            OKSYWIE: 'Oksywie',
            ORLOWO: 'Orłowo',
            POGORZE: 'Pogórze',
            PUSTKI_CISOWSKIE_DEMPTOWO: 'Pustki Cisowskie-Demptowo',
            REDLOWO: 'Redłowo',
            SRODMIESCIE: 'Śródmieście',
            WIELKI_KACK: 'Wielki Kack',
            WITOMINO_LESNICZOWKA: 'Witomino-Leśniczówka',
            WITOMINO_RADIOSTACJA: 'Witomino-Radiostacja',
            WZGORZE_SWIETEGO_MAKSYMILIANA: 'Wzgórze Świętego Maksymiliana',
        },
        GLIWICE: {
            BOJKOW: 'Bojków',
            BRZEZINKA: 'Brzezinka',
            CZECHOWICE: 'Czechowice',
            KOPERNIKA: 'Kopernika',
            LIGOTA_ZABRSKA: 'Ligota Zabrska',
            LABEDY: 'Łabędy',
            OBRONCOW_POKOJU: 'Obrońców Pokoju',
            OSTROPA: 'Ostropa',
            POLITECHNIKA: 'Politechnika',
            SIKORNIK: 'Sikornik',
            SOSNICA: 'Sośnica',
            STARE_GLIWICE: 'Stare Gliwice',
            SZOBISZOWICE: 'Szobiszowice',
            SRODMIESCIE: 'Śródmieście',
            TRYNEK: 'Trynek',
            WILCZE_GARDLO: 'Wilcze Gardło',
            WOJSKA_POLSKIEGO: 'Wojska Polskiego',
            WOJTOWA_WIES: 'Wójtowa Wieś',
            ZATORZE: 'Zatorze',
            ZERNIKI: 'Żerniki',
        },
        KATOWICE: {
            BLESZNO: 'Błeszno',
            DZBOW: 'Dźbów',
            GRABOWKA: 'Grabówka',
            KAWODRZA: 'Kawodrza',
            KIEDRZYN: 'Kiedrzyn',
            LISINIEC: 'Lisiniec',
            MIROW: 'Mirów',
            OSTATNI_GROSZ: 'Ostatni Grosz',
            PARKITKA: 'Parkitka',
            PODJASNOGORSKA: 'Podjasnogórska',
            POLNOC: 'Północ',
            RAKOW: 'Raków',
            STARE_MIASTO: 'Stare Miasto',
            STRADOM: 'Stradom',
            SRODMIESCIE: 'Śródmieście',
            TRZECH_WIESZCZOW: 'Trzech Wieszczów',
            TYSIACLECIE: 'Tysiąclecie',
            WRZOSOWIAK: 'Wrzosowiak',
            WYCZERPY_ANIOLOW: 'Wyczerpy - Aniołów',
            ZAWODZIE_DABIE: 'Zawodzie - Dąbie',
        },
        CZESTOCHOWA: {
            BLESZNO: 'Błeszno',
            DZBOW: 'Dźbów',
            GRABOWKA: 'Grabówka',
            KAWODRZA: 'Kawodrza',
            KIEDRZYN: 'Kiedrzyn',
            LISINIEC: 'Lisiniec',
            MIROW: 'Mirów',
            OSTATNI_GROSZ: 'Ostatni Grosz',
            PARKITKA: 'Parkitka',
            PODJASNOGORSKA: 'Podjasnogórska',
            POLNOC: 'Północ',
            RAKOW: 'Raków',
            STARE_MIASTO: 'Stare Miasto',
            STRADOM: 'Stradom',
            SRODMIESCIE: 'Śródmieście',
            TRZECH_WIESZCZOW: 'Trzech Wieszczów',
            TYSIACLECIE: 'Tysiąclecie',
            WRZOSOWIAK: 'Wrzosowiak',
            WYCZERPY_ANIOLOW: 'Wyczerpy - Aniołów',
            ZAWODZIE_DABIE: 'Zawodzie - Dąbie',
        },
        BIALYSTOK: {
            ANTONIUK: 'Antoniuk',
            BACIECZKI: 'Bacieczki',
            BEMA: 'Bema',
            BIALOSTOCZEK: 'Białostoczek',
            BOJARY: 'Bojary',
            CENTRUM: 'Centrum',
            DOJLIDY: 'Dojlidy',
            DOJLIDY_GORNE: 'Dojlidy Górne',
            DZIESIECINY_I: 'Dziesięciny I',
            DZIESIECINY_II: 'Dziesięciny II',
            JAROSZOWKA: 'Jaroszówka',
            KAWALERYJSKIE: 'Kawaleryjskie',
            LESNA_DOLINA: 'Leśna Dolina',
            MICKIEWICZA: 'Mickiewicza',
            MLODYCH: 'Młodych',
            NOWE_MIASTO: 'Nowe Miasto',
            PIASKI: 'Piaski',
            PIASTA_I: 'Piasta I',
            PIASTA_II: 'Piasta II',
            PRZYDWORCOWE: 'Przydworcowe',
            SIENKIEWICZA: 'Sienkiewicza',
            SKORUPY: 'Skorupy',
            SLONECZNY_STOK: 'Słoneczny Stok',
            STAROSIELCE: 'Starosielce',
            WYGODA: 'Wygoda',
            WYSOKI_STOCZEK: 'Wysoki Stoczek',
            ZAWADY: 'Zawady',
            ZIELONE_WZGORZA: 'Zielone Wzgórza',
        },
        LODZ: {
            BALUTY: 'Bałuty',
            GORNA: 'Górna',
            POLESIE: 'Polesie',
            SRODMIESCIE: 'Śródmieście',
            WIDZEW: 'Widzew',
        },
        ZIELONAGORA: {
            CENTRUM: 'Centrum',
            CIEPLOCH: 'Ciepłoch',
            CZERWONA_DABROWKA: 'Czerwona Dąbrówka',
            DROZDZYN: 'Droźdzyn',
            NOWE_MIASTO: 'Nowe Miasto',
            STARE_MIASTO: 'Stare Miasto',
            WILCZE_DOLY: 'Wilcze Doły',
            WZGORZE_WOJSZYCKIE: 'Wzgórze Wojszyckie',
        },
    },
};
module.exports = {callbacks};